[publisher.pythd]
endpoint = 'ws://127.0.0.1:8910'

[publisher.coin_gecko]
update_interval_secs = 15
confidence_ratio_bps = 10

[[ publisher.products ]]
pythd_symbol = 'Crypto.BTC/USD'
coin_gecko_id = 'bitcoin'
