[publisher]

# Set it to either 'coin_gecko' or 'pyth_replicator'. You need to provide
# the configuration for the chosen engine as described below.
provider_engine = "jetfuel"

price_update_interval_secs = 1.0
product_update_interval_secs = 60
health_check_port = 8000

# The health check will return a failure status if no price data has been published within the specified time frame.
health_check_threshold_secs = 60

[publisher.pythd]
endpoint = 'ws://127.0.0.1:8910'

# [publisher.coin_gecko]
# update_interval_secs = 15
# confidence_ratio_bps = 10

# [[publisher.coin_gecko.products]]
# symbol = 'Crypto.BTC/USD'
# coin_gecko_id = 'bitcoin'

[publisher.pyth_replicator]
http_endpoint = 'https://api2.pythnet.pyth.network'
ws_endpoint = 'wss://api2.pythnet.pyth.network'
first_mapping = 'AHtgzX45WTKfkPG53L6WYhGEXwQkN1BVknET3sVsLL8J'
program_key = 'FsJ3A3u2vn5cTVofAjvy6y5kwABJAqYWpe4975bi2epH'

[publisher.jetfuel]
fred_api_key   = "${FRED_API_KEY}"      # verrà letto dal secret GitHub
price_account  = "${PYTH_PRICE_ACCOUNT}"
update_secs    = 3600                   # una volta l’ora
